# ----
# Site

title: Prusaat
url: "https://prusaat.netlify.app/"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"
snipcart_currency: "usd"

logo: /siteicon.png
description: Prusaat | Zamandan Fazlası
author:
  name: prusaat
  email: prusaat@gmail.com
  twitter: fur # twitter username without the @ symbol
  phone: "+90 xxxxxxxx"
social:
  name: Prusaat | Zamandan Fazlası
  links:
    - 

# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Email
  - Instagram

